const { writeFileSync, existsSync, mkdirSync } = require('fs');
const { resolve } = require('path');

// Get version from package.json
const { version } = require('../package.json');

console.log("starting set-version script...");
// Define the content for the version file
const content = `// IMPORTANT: THIS FILE IS AUTO GENERATED!
// Do not edit this file directly.
export const version = '${version}';
`;

// Define the path for the environments folder and the version file
const envDir = resolve(__dirname, '..', 'src', 'environments');
const targetPath = resolve(envDir, 'version.ts');

// Create the environments directory if it doesn't exist
if (!existsSync(envDir)) {
  mkdirSync(envDir);
}

// Write the version file
writeFileSync(targetPath, content, { encoding: 'utf8' });

console.log(`Wrote version ${version} to ${targetPath}`);
