name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master # Or your default branch where your Angular code lives

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for actions/checkout
      pages: write    # Needed for actions/deploy-pages
      id-token: write # Needed for OIDC authentication with deploy-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or the Node.js version your Angular app requires

      - name: Install dependencies
        run: npm ci

      - name: Increase Version Bump
        id: version_bump_step # Add an ID to reference outputs if needed later
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: '$COMMIT_MESSAGE'"

          INCREMENT_TYPE="none" # Default to no bump

          # Check for a BREAKING CHANGE first (highest precedence)
          if echo "$COMMIT_MESSAGE" | grep -qE "(^feat!:|^fix!:|^BREAKING CHANGE:)"; then
              INCREMENT_TYPE="major"
          elif [[ "$COMMIT_MESSAGE" == "feat:"* ]]; then # Check for "feat:" at the beginning
              INCREMENT_TYPE="minor"
          elif [[ "$COMMIT_MESSAGE" == "fix:"* ]]; then # Check for "fix:" at the beginning
              INCREMENT_TYPE="patch"
          fi

          if [ "$INCREMENT_TYPE" = "none" ]; then
              echo "No semantic versioning keyword (feat:, fix:, BREAKING CHANGE:) found. Skipping version increment."
              exit 0 # Exit successfully without changing version or pushing
          fi

          echo "Detected increment type: $INCREMENT_TYPE"

          # Run your versioning script with the determined type
          node scripts/set-version.js "$INCREMENT_TYPE"

          echo "Configuring Git user..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Staging modified files..."
          git add package.json
          git add src/environments/version.ts

          # Check if there are actual changes to commit
          if ! git diff --cached --exit-code; then
              echo "Changes detected, creating new version commit..."
              # Get the new version from package.json for the commit message
              NEW_VERSION=$(node -p "require('./package.json').version")
              # Use [skip ci] to prevent this commit from triggering another workflow run
              git commit -m "chore(release): auto-bump to ${NEW_VERSION} ($INCREMENT_TYPE) [skip ci]"

              echo "Pushing new version commit to branch..."
              git push
          else
              echo "No version changes were actually made by the script. Skipping commit and push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Angular application
        # This is where your Angular build command goes.
        # Ensure --base-href is correct for your GitHub Pages URL.
        # Replace 'YOUR_REPOSITORY_NAME' with your actual repository name.
        run: npm run build -- --base-href=/portfolio-fernando-ballarini/
        env:
          NODE_OPTIONS: --max_old_space_size=8192 # Optional: Increase if you get memory errors during build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # This is CRUCIAL. It must point to your Angular build output directory.
        # After `ng build`, your app is usually in 'dist/your-app-name'.
        # Check your `angular.json` or your `dist` folder after a local build to confirm the path.
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs # <--- Make sure this path is correct for your Angular app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
